// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qeRUZNroROFHd-CuQ94eRCTKRE01UB4',
    appId: '1:467731776942:web:1f0aff0fcd30ebb681f43f',
    messagingSenderId: '467731776942',
    projectId: 'crud-e5f93',
    authDomain: 'crud-e5f93.firebaseapp.com',
    storageBucket: 'crud-e5f93.appspot.com',
    measurementId: 'G-DZJGMFXZV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnPmGmv0N3N-xoTahaHOtDFMocvSRFgc',
    appId: '1:467731776942:android:b19d23da7263608581f43f',
    messagingSenderId: '467731776942',
    projectId: 'crud-e5f93',
    storageBucket: 'crud-e5f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTFczlPkBSypolG7eKDTV_nFGIJaJ8LX8',
    appId: '1:467731776942:ios:3d1136f1bed2909a81f43f',
    messagingSenderId: '467731776942',
    projectId: 'crud-e5f93',
    storageBucket: 'crud-e5f93.appspot.com',
    iosClientId:
        '467731776942-606gnj54s00ltsdt8vtcmm3lt59rrs61.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
